type Store {
  name: String! @unique
  products: [ProductPrice_Store] @relation(name: "store_products")
  bills: [Bill] @relation(name: "store_bills")
}

type ProductPrice_Store {
  store: Store! @relation(name: "store_products")
  product: Product! @relation(name: "price_product")
  price: Float!
}
type Product {
  name: String! @unique
  price: [ProductPrice_Store]! @relation(name: "price_product")
  bills: [Bill]! @relation(name: "product_on_bill")
}

type Bill {
  store: Store! @relation(name: "store_bills")
  products: [Product!] @relation(name: "product_on_bill")
  total: Float
  date: Date!
}

type Query {
  allStores: [Store!]
  allProducts: [Product!]
  allBills: [Bill!]
  store(name: String!): [Store]
  product(name: String!): [Product]
}
